### ISSUE TITLE
高速模式微信最新（6.6.2）控件id

### ISSUE THREAD

**Issue by Frog9527** [secondfeeling/Hello-World#4]
开红包：com.tencent.mm:id/c4j
退出红包：com.tencent.mm:id/hx
聊天窗口红包：com.tencent.mm:id/ad8
聊天列表每个item：com.tencent.mm:id/app
（聊天列表item）新消息红点：com.tencent.mm:id/j4
（聊天列表item）消息内容textview：com.tencent.mm:id/apt
红包备注：com.tencent.mm:id/ae9
查看红包按钮：com.tencent.mm:id/ae_

对应的修改这些6.6.2版本微信的高速模式就可以用了（已验证）
    // 微信 聊天列表的联系人里面的消息内容 不可点击
    public final static String WID_CHAT_LIST_MESSAGE_TEXT = "com.tencent.mm:id/apt";
    // 微信 聊天列表的联系人 内括名字、消息内容、消息数字、头像  可点击
    public final static String WID_CHAT_LIST_DIALOG = "com.tencent.mm:id/app";
    // 微信 聊天列表的联系人里面的消息数字 不可点击
    public final static String WID_CHAT_LIST_MESSAGE_NUM = "com.tencent.mm:id/j4";
    // 微信 聊天窗口 收到红包 可点击
    public final static String WID_CHAT_DIALOG_PACKET = "com.tencent.mm:id/ad8";
    // 微信 聊天窗口 收到红包 红包的文字（领取红包/查看红包） 不可点击
    public final static String WID_CHAT_DIALOG_PACKET_TEXT = "com.tencent.mm:id/ae_";
    // 微信 聊天窗口 收到红包 红包的文字内容 不可点击
    public final static String WID_CHAT_DIALOG_PACKET_CONTENT = "com.tencent.mm:id/ae9";
    // 微信 聊天窗口 打开红包弹窗  “開”
    public final static String WID_CHAT_PACKET_DIALOG_BUTTON = "com.tencent.mm:id/c4j";

**Comment by summer9966** [comment]
感谢，后续会更新。如果有时间，可以帮忙看看，为什么有的机型，特别是MIUI9，会偶现卡在最后拆开红包的界面，这个问题困扰我许久了。

**Comment by Frog9527** [comment]
用的6.6.2的微信 MIUI9.2|稳定版（红米5 plus）试了多次
高速模式：未出现卡住的情况
兼容模式：有出现卡在“开”界面。修改了openPacket(AccessibilityNodeInfo rootNode)这个方法下面几行代码后未再出现
//                    if (nodeInfo.isClickable()) {
//                        eventScheduling.addOpenPacketList(nodeInfo);
//                        result = true;
//                    }
替换为：
                    if (nodeInfo.getClassName().toString().equals("android.widget.Button")) {
                        if (nodeInfo.isEnabled()) { 
                            eventScheduling.addOpenPacketList(nodeInfo);
                            result = true;
                        }
                    }

**Comment by summer9966** [comment]
感谢，目前发现，好像是和android版本（8.0）有关，我使用红米note3 MIUI9开发版也没有发现这问题。

但是，在小米6、小米mix2上有出现这样的现象。
